apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-iuuw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fqkd-tenant/rhtap-demo-app/hacbs-test-project-iuuw@sha256:f40bd1ddf9456eb49af8e3bac0a4ba8eda3f67f667a4180b21d1192934b6d05f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
