apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-iuuw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fqkd-tenant/rhtap-demo-app/hacbs-test-project-iuuw@sha256:753ccf41b71c07261aca569eecd78a750c27e5b5e82377cc33f56e1204a4ec7a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
