apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-iuuw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-iuuw
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-iuuw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-iuuw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-iuuw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fqkd-tenant/rhtap-demo-app/hacbs-test-project-iuuw@sha256:fee5b2a318240377db2ac3b2485437ad204280eac24ea3649edf5d9057477771
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
